### ISSUE TITLE
Custom device type 

### ISSUE THREAD

**Issue by GwennanS** [IssaHanou/BEP_1920_Q2#132]
### Content
Right now, we have the device types for input for string, boolean, numeric and array. A custom type that does not define one of those might be needed.

### Feature
custom type for in/output for devices is possible

**Comment by IssaHanou** [comment]
As discussed in the meeting with the client on January 13, this is okay to leave as TODO's in the code.

Currently there is no need for custom types, but the ability to add them later should remain with as is.
