### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by mrlomar** [IssaHanou/BEP_1920_Q2#21]
### Content
The back-end should manage an escape room based on its configuration and input from client computers.

### Feature
The back-end must send instructions to client computers based on input from client computers and information from the configuration file. 

### Action plan
This will be implemented through issues GH-25, GH-22, GH-30, GH-20
[ ] isolate message handling

**Comment by IssaHanou** [comment]
A part was done in issue GH-6, but the rest was waiting for issue GH-22 as it is config based. The latter was finished on friday, therefore, this issue is moved to sprint 2
