### ISSUE TITLE
Client computer communication

### ISSUE THREAD

**Issue by mrlomar** [IssaHanou/BEP_1920_Q2#25]
### Content
A client computer should be able to process messages from the back-end.

### Feature
- A client computer must be able to receive an instruction message from the back-end.
- A client computer must be able to determine whether to act upon a received message and which device to trigger.

### Action Plan
This will mainly be done through issue GH-27

**Comment by GwennanS** [comment]
Client devices now process all incoming messages, but the same way for each topic
