### ISSUE TITLE
Implement test device

### ISSUE THREAD

**Issue by IssaHanou** [IssaHanou/BEP_1920_Q2#27]
### Content
In order to have a minimal communication set-up, there must be a device which is implemented to handle request. Preferably, this should be done using the client computer library that will be used in the project. 

### Feature
- Implement basic library 
- Implement device logic (for testing use only)

### Action plan
- [x] Create client computer library with basic handler for minimal communciation features
- [x] Implement device to actually function upon instructions from back-end

### Related issues
GH-25

**Comment by GwennanS** [comment]
The control board is now controllable for the LEDs and the switches. in cc_library/src/scripts is start_device.py and example_config.json is hardcoded for the device, but cc_library/src/device/app.py is not and will be the start of the library for every device.

**Comment by GwennanS** [comment]
Hardware is not very reliable yet but there are 2 test devices implemented
