### ISSUE TITLE
Test the cc_library 

### ISSUE THREAD

**Issue by GwennanS** [IssaHanou/BEP_1920_Q2#52]
### Content
There is a start of a library but it does not have any tests to guarantee reliability
 
### Feature
Unit tests need to be implemented for all code in cc_library

### Action plan
- [ ] figure out what to test how
- [ ] implement tests

### Related issues
GH-25

**Comment by IssaHanou** [comment]
This issue was closed as it was not relevant as such a specific issue and the more generic testing issue GH-67 was opened instead.
