### ISSUE TITLE
System testing

### ISSUE THREAD

**Issue by IssaHanou** [IssaHanou/BEP_1920_Q2#67]
### Content
The system should be tested as a whole: a script starting up the devices and connecting with the back- and front-end. 

### Feature
- The system should be tested as a whole.

### Related issues
A general issue for testing, which closes the too specific issues GH-15 and GH-52 that were decided to not work on in week 4. 

- [ ] Create a client computer that continually sends status messages and see if back-end can handle it 
- [ ] Test if the QoS setting works after disconnecting a broker, sending a status, and connecting a broker
- [ ] button true-false messages, does is trigger the right amount of rules

**Comment by GwennanS** [comment]
https://www.admfactory.com/how-to-install-golang-on-raspberry-pi/

**Comment by GwennanS** [comment]
https://saintcoder.wordpress.com/2017/01/28/how-to-setup-your-first-go-langs-workspace-and-run-your-1st-hello-world-in-your-linux-box/
