### ISSUE TITLE
Create scclib package

### ISSUE THREAD

**Issue by IssaHanou** [IssaHanou/BEP_1920_Q2#88]
### Content
The client computer library must be downloadable as a package:

https://packaging.python.org/tutorials/packaging-projects/

**Comment by GwennanS** [comment]
try ```pip install --index-url https://test.pypi.org/simple/ --no-deps scclib``` plz

**Comment by GwennanS** [comment]
alright, how to do it:
in setup.py: ```        "License :: OSI Approved :: GNU General Public License v3 (GPLv3)", ``` and ```python_requires=">=3.5",``` instead of what it is now

 pip install twine and wheel

run ```python setup.py sdist bdist_wheel```
run ```python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/* ```

**Comment by GwennanS** [comment]
https://test.pypi.org/project/scclib/
